services:
  - type: web
    name: smart-invoice
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_invoice.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --worker-class gthread --worker-tmp-dir /dev/shm --log-file - --access-logfile - --error-logfile - --timeout 120 --keep-alive 5"
    preDeployCommand: "python manage.py migrate --no-input && python manage.py createcachetable && python manage.py check_overdue_invoices"
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false

databases:
  - name: smart-invoice-db
    databaseName: smartinvoice
    plan: starter
