services:
  - type: web
    name: smart-invoice
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn smart_invoice.wsgi:application
    publishDirectory: ./
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smart_invoice.settings
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        sync: false
