# Generated by Django 5.2.7 on 2025-10-22 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('business_email', models.EmailField(blank=True, max_length=200, verbose_name='Business Email')),
                ('business_address', models.TextField(blank=True, verbose_name='Business Address')),
                ('business_phone', models.CharField(blank=True, max_length=50, verbose_name='Business Phone')),
                ('business_logo_url', models.URLField(blank=True, max_length=500, verbose_name='Business Logo URL')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('client_email', models.EmailField(blank=True, max_length=200, verbose_name='Client Email')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Client Phone/WhatsApp')),
                ('client_address', models.TextField(blank=True, verbose_name='Client Address')),
                ('description', models.TextField(default='', verbose_name='Service/Product Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Price')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('NGN', 'Naira (NGN)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Due Immediately'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days')], default='net_30', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('payment_instructions', models.TextField(blank=True, verbose_name='Payment Instructions')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
