# Generated by Django 5.2.7 on 2025-10-21 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email_or_whatsapp', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Naira (NGN)'), ('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)')], default='NGN', max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
