# Generated by Django 5.2.7 on 2025-10-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_user'),
        ('invoices', '0002_supportinquiry_invoice_paystack_reference'),
    ]

    operations = [
    ]
