# Generated by Django 5.2.7 on 2025-10-24 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicelineitem_paymenttransaction_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='invoices_in_client__c4d581_idx'),
        ),
    ]
