# Generated by Django 5.2.7 on 2025-10-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_invoices_in_client__c4d581_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice', 'order'], name='invoices_in_invoice_e3de44_idx'),
        ),
    ]
